#!/usr/bin/env bash
set -euo pipefail

REPO="/Users/jan/Documents/Claude/zllhff.github.io"
mkdir -p "$REPO/assets/icons"
for app in faro roll kept shin vow; do
  mkdir -p "$REPO/assets/screenshots/$app/de" "$REPO/assets/screenshots/$app/en"
done

# --- Icons ---
# Sources from .xcarchive builds are Apple-optimized PNGs (CgBI chunk), which
# standard browsers cannot render. Re-encode through `sips -s format png` to
# strip CgBI and produce a standard PNG. Faro/Kept/Shin only have a 120x120
# flattened archive render available (no higher-res source on disk), so they
# are re-encoded at native size. Roll and Vow have real 1024x1024 sources and
# are downsampled to 480 for a crisper result at the larger tile size.
icon_native() {
  local src="$1" dest="$2"
  sips -s format png "$src" --out "$dest" >/dev/null
}
icon_hq() {
  local src="$1" dest="$2"
  sips -s format png --resampleWidth 480 "$src" --out "$dest" >/dev/null
}
icon_native "/Users/jan/Documents/Claude/Faro/build/Faro.xcarchive/Products/Applications/Faro.app/Faro60x60@2x.png" \
  "$REPO/assets/icons/faro.png"
icon_hq "/Users/jan/Documents/Claude/roll/src/Roll/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png" \
  "$REPO/assets/icons/roll.png"
icon_native "/Users/jan/Documents/Claude/kept app/release/Filed.xcarchive/Products/Applications/Filed.app/AppIcon60x60@2x.png" \
  "$REPO/assets/icons/kept.png"
icon_native "/Users/jan/Documents/Claude/shin app/.asc/artifacts/Shin-1.2.1-11.xcarchive/Products/Applications/shin.app/AppIcon60x60@2x.png" \
  "$REPO/assets/icons/shin.png"
# Vow's source is the current post-rename "unbroken ring" icon (Icon Composer
# asset catalog), not the stale pre-rename Debug-simulator build product.
icon_hq "/Users/jan/Documents/Claude/Still/Still/Assets.xcassets/AppIcon.appiconset/icon_light.png" \
  "$REPO/assets/icons/vow.png"

# --- Screenshots: resize to 480px width, convert to JPEG quality 82 ---
resize() {
  local src="$1" dest="$2"
  sips -s format jpeg -s formatOptions 82 --resampleWidth 480 "$src" --out "$dest" >/dev/null
}

FARO_SHOTS=(01-hero 02-anchor 04-challenge 05a-atlas 06-landfall)
i=1
for shot in "${FARO_SHOTS[@]}"; do
  resize "/Users/jan/Documents/Claude/Faro/store_assets/screenshots/de-DE/$shot.png" "$REPO/assets/screenshots/faro/de/$i.jpg"
  resize "/Users/jan/Documents/Claude/Faro/store_assets/screenshots/en-US/$shot.png" "$REPO/assets/screenshots/faro/en/$i.jpg"
  i=$((i + 1))
done

ROLL_SHOTS=(scene-01-hero scene-02-cleanup scene-03-decide scene-04-fullscreen scene-05-compare)
i=1
for shot in "${ROLL_SHOTS[@]}"; do
  resize "/Users/jan/Documents/Claude/roll/store_assets/screenshots/de/raw/$shot.png" "$REPO/assets/screenshots/roll/de/$i.jpg"
  resize "/Users/jan/Documents/Claude/roll/store_assets/screenshots/en/raw/$shot.png" "$REPO/assets/screenshots/roll/en/$i.jpg"
  i=$((i + 1))
done

# Kept uses 5 visually distinct marketing screenshots (English UI). The older
# ASC raw set (library/actions/search) was three near-identical list views, so
# it was replaced. The same 5 serve both languages (no localized marketing set).
KEPT_SRC="/Users/jan/Documents/Claude/kept app/marketing/x-assets-2026-07/screenshots"
KEPT_SHOTS=(01-library 06-viewer 07-inspector 08-cancellation 14-library-light)
i=1
for shot in "${KEPT_SHOTS[@]}"; do
  resize "$KEPT_SRC/$shot.png" "$REPO/assets/screenshots/kept/de/$i.jpg"
  resize "$KEPT_SRC/$shot.png" "$REPO/assets/screenshots/kept/en/$i.jpg"
  i=$((i + 1))
done

SHIN_SHOTS=(6_9_01_hero 6_9_02_today 6_9_03_tie 6_9_04_deep_dive 6_9_05_letter)
i=1
for shot in "${SHIN_SHOTS[@]}"; do
  resize "/Users/jan/Documents/Claude/shin app/store_assets/screenshots/de-DE/$shot.png" "$REPO/assets/screenshots/shin/de/$i.jpg"
  resize "/Users/jan/Documents/Claude/shin app/store_assets/screenshots/en-US/$shot.png" "$REPO/assets/screenshots/shin/en/$i.jpg"
  i=$((i + 1))
done

# Vow screenshots are captured from the simulator (no App Store set yet) and
# committed directly, not regenerated by this script. Slots: 1 home, 2 active
# session (Forest world), 3 active session (Night sky world), 4 settings,
# 5 paywall. The two active-session screens show a "mode active" state in two
# different worlds.
echo "Done. Vow screenshots are captured from the simulator and committed directly, not handled by this script."
